language: ruby
before_script:
  - mysql -e 'create database delayed_job_test;'
  - psql -c 'create database delayed_job_test;' -U postgres
script: bundle exec rspec
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug"
gemfile:
  - gemfiles/mysql/4-0.gemfile
  - gemfiles/mysql/4-1.gemfile
  - gemfiles/mysql/4-2.gemfile
  - gemfiles/mysql2/5-0.gemfile
  - gemfiles/mysql2/5-1.gemfile
  - gemfiles/postgresql/4-0.gemfile
  - gemfiles/postgresql/4-1.gemfile
  - gemfiles/postgresql/4-2.gemfile
  - gemfiles/postgresql/5-0.gemfile
  - gemfiles/postgresql/5-1.gemfile
  - gemfiles/sqlite3/4-0.gemfile
  - gemfiles/sqlite3/4-0-protected_attributes.gemfile
  - gemfiles/sqlite3/4-1.gemfile
  - gemfiles/sqlite3/4-2.gemfile
  - gemfiles/sqlite3/5-0.gemfile
  - gemfiles/sqlite3/5-1.gemfile
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby
  - rbx-2

jdk: oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
    - gemfile: gemfiles/mysql2/master.gemfile
    - gemfile: gemfiles/postgresql/master.gemfile
    - gemfile: gemfiles/sqlite3/master.gemfile

  include: # The Future
    - gemfile: gemfiles/mysql2/master.gemfile
      rvm: 2.4.1
    - gemfile: gemfiles/postgresql/master.gemfile
      rvm: 2.4.1
    - gemfile: gemfiles/sqlite3/master.gemfile
      rvm: 2.4.1

    - rvm: ruby-head
      gemfile: gemfiles/mysql/4-2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/postgresql/4-2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sqlite3/4-2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sqlite3/5-1.gemfile

    - rvm: jruby-head
      gemfile: gemfiles/mysql/4-2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/mysql2/5-0.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/postgresql/4-2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/sqlite3/4-2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/sqlite3/5-1.gemfile

sudo: false
